name: RLSRWP_2025
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - kat>=2.4.2
  - curl>=7.73.0
  - fastqc>=0.12.1
  - multiqc>=1.6
  - fastp>=0.23.4
  - samtools>=1.20
  - bowtie2>=2.5.4
  - seqtk>=1.4
  - bioconductor-maftools
  - pip:
      - .  # . installs varseek from pyproject.toml