name: RLSRWP_2025
channels:
  - bioconda
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python==3.10
  - pip
  - curl>=7.73.0
  - fastqc>=0.12.1
  - multiqc>=1.6
  - fastp>=0.23.4
  - samtools>=1.20
  - bowtie2>=2.5.4
  - seqtk>=1.4
  - bioconductor-maftools>=2.6.05
  - gffread>=0.12.7
  - openmm=7.7.0
  - bcftools=1.21
  - pip:
      - .  # . installs varseek from pyproject.toml